name: Run CI Build on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  test-and-build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add required .env file
        run: |
          {
            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}"
            echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          } >> .env
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
