name: Deploy to Firebase Hosting on push to main
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add required .env file
        run: |
          {
            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}"
            echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          } >> .env
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEAL_CODES }}
          projectId: seal-codes
          channelID: live
